package solr.jdbc.impl;

import java.io.StringReader;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.SQLWarning;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;

import net.sf.jsqlparser.JSQLParserException;
import net.sf.jsqlparser.parser.CCJSqlParserManager;

import solr.jdbc.command.Command;
import solr.jdbc.command.CommandFactory;
import solr.jdbc.message.DbException;
import solr.jdbc.message.ErrorCode;

public class StatementImpl implements Statement {
	private static final int MAX_FETCH_SIZE = 10000;

	protected SolrConnection conn;
	protected AbstractResultSet resultSet;
	protected int updateCount;
	
	private List<String> batchCommands;
	private boolean isClosed = false;
	private int maxRows;
	private boolean escapeProcessing = true;

	protected int fetchSize = MAX_FETCH_SIZE;
	protected final int resultSetType;
	protected final int resultSetConcurrency;
	protected boolean closedByResultSet;

	public StatementImpl(SolrConnection conn, int resultSetType, int resultSetConcurrency) {
		this.conn = conn;
		this.resultSetType = resultSetType;
		this.resultSetConcurrency = resultSetConcurrency;
	}
	
	private Command parseSQL(String sql) throws SQLException {
		Command command = null;
		CCJSqlParserManager pm = new CCJSqlParserManager();
		try {
			net.sf.jsqlparser.statement.Statement statement = pm.parse(new StringReader(sql));
			command = CommandFactory.getCommand(statement);
			command.setConnection(conn);
			command.parse();
		} catch (JSQLParserException ex) {
			throw new SQLException(ex);
		}
		return command;

	}

	@Override
	public void addBatch(String sql) throws SQLException {
		checkClosed();
		if (batchCommands == null) {
			batchCommands = new ArrayList<String>();
		}
		batchCommands.add(sql);

	}

	@Override
	public void cancel() throws SQLException {
	}

	@Override
	public void clearBatch() throws SQLException {
        checkClosed();
        batchCommands = null;
	}

	@Override
	public void clearWarnings() throws SQLException {
		checkClosed();
		// Do nothing
	}

	@Override
	public void close() throws SQLException {
		conn = null;
		isClosed = true;
	}

	private boolean executeInternal(String sql) throws SQLException {
		Command command = parseSQL(sql);
		try {
			if(command.isQuery()) {
				resultSet = (AbstractResultSet)command.executeQuery();
			} else {
				updateCount = command.executeUpdate();
			}
			command.executeUpdate();
		} catch (DbException e) {
			throw e.getSQLException();
		}
		return true;
	}

	@Override
	public boolean execute(String sql) throws SQLException {
		checkClosed();
		return executeInternal(sql);
	}

	@Override
	public boolean execute(String sql, int autoGeneratedKeys)
			throws SQLException {
		checkClosed();
		return executeInternal(sql);
	}

	@Override
	public boolean execute(String sql, int[] columnIndexes) throws SQLException {
		checkClosed();
		return executeInternal(sql);
	}

	@Override
	public boolean execute(String sql, String[] columnNames)
			throws SQLException {
		checkClosed();
		return executeInternal(sql);
	}

	@Override
	public int[] executeBatch() throws SQLException {
		checkClosed();
		if (batchCommands == null) {
			batchCommands = new ArrayList<String>();
		}
		int[] result = new int[batchCommands.size()];
		boolean error = false;

		for (int i = 0; i < batchCommands.size(); i++) {
			String sql = batchCommands.get(i);
			try {
				result[i] = executeUpdate(sql);
			} catch(Exception e) {
				logAndConvert(e);
				result[i] = Statement.EXECUTE_FAILED;
				error = true;
			}
		}
		batchCommands = null;
		return result;
	}

	@Override
	public ResultSet executeQuery(String sql) throws SQLException {
		checkClosed();
		Command command = parseSQL(sql);
		try {
			return command.executeQuery();
		} catch (DbException e) {
			throw e.getSQLException();
		}
	}

	@Override
	public int executeUpdate(String sql) throws SQLException {
		checkClosed();
		Command command = parseSQL(sql);
		try {
			return command.executeUpdate();
		} catch (DbException e) {
			throw e.getSQLException();
		}
	}

	@Override
	public int executeUpdate(String sql, int autoGeneratedKeys)
			throws SQLException {
		// TODO Auto-generated method stub
		return 0;
	}

	@Override
	public int executeUpdate(String sql, int[] columnIndexes)
			throws SQLException {
		// TODO Auto-generated method stub
		return 0;
	}

	@Override
	public int executeUpdate(String sql, String[] columnNames)
			throws SQLException {
		// TODO Auto-generated method stub
		return 0;
	}

	@Override
	public Connection getConnection() throws SQLException {
		return conn;
	}

	@Override
	public ResultSet getGeneratedKeys() throws SQLException {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public boolean getMoreResults() throws SQLException {
		// TODO Auto-generated method stub
		return false;
	}

	@Override
	public boolean getMoreResults(int current) throws SQLException {
		// TODO Auto-generated method stub
		return false;
	}

	@Override
	public ResultSet getResultSet() throws SQLException {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public int getResultSetConcurrency() throws SQLException {
		// TODO Auto-generated method stub
		return 0;
	}

	@Override
	public int getResultSetHoldability() throws SQLException {
		// TODO Auto-generated method stub
		return 0;
	}

	@Override
	public int getResultSetType() throws SQLException {
		// TODO Auto-generated method stub
		return 0;
	}

	@Override
	public int getUpdateCount() throws SQLException {
		// TODO Auto-generated method stub
		return 0;
	}

	@Override
	public SQLWarning getWarnings() throws SQLException {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public boolean isClosed() throws SQLException {
		return isClosed();
	}

	@Override
	public boolean isPoolable() throws SQLException {
		return false;
	}

	@Override
	public void setCursorName(String name) throws SQLException {
		checkClosed();
	}

	@Override
	public void setEscapeProcessing(boolean enable) throws SQLException {
		checkClosed();
		escapeProcessing = enable;
	}

	@Override
	public int getFetchDirection() throws SQLException {
		checkClosed();
		return ResultSet.FETCH_FORWARD;
	}

	@Override
	public void setFetchDirection(int direction) throws SQLException {
		checkClosed();
	}

	@Override
	public int getFetchSize() throws SQLException {
		checkClosed();
		return fetchSize;
	}

	@Override
	public void setFetchSize(int rows) throws SQLException {
		checkClosed();

		try {
			if (rows < 0 || (rows > 0 && maxRows > 0 && rows > maxRows)) {
				throw DbException.getInvalidValueException("" + rows, "rows");
			}
			if (rows == 0) {
				rows = MAX_FETCH_SIZE;
			}
			fetchSize = rows;

		} catch (Exception e) {
			logAndConvert(e);
		}

	}

    @Override
	public int getMaxFieldSize() throws SQLException {
		return 0;
	}

	/**
     * Sets the maximum number of bytes for a result set column.
     * This method does currently do nothing for this driver.
     *
     * @param max the maximum size - ignored
     * @throws SQLException if this object is closed
     */
	@Override
	public void setMaxFieldSize(int max) throws SQLException {
		checkClosed();
	}

	@Override
	public int getMaxRows() throws SQLException {
		checkClosed();
		return 0;
	}

	@Override
	public void setMaxRows(int max) throws SQLException {
		this.maxRows = max;
	}

	@Override
	public void setPoolable(boolean poolable) throws SQLException {
		// ignore
	}

	@Override
	public int getQueryTimeout() throws SQLException {
		// TODO Auto-generated method stub
		return 0;
	}

	@Override
	public void setQueryTimeout(int seconds) throws SQLException {
		// TODO Auto-generated method stub

	}

	@Override
	public boolean isWrapperFor(Class<?> iface) throws SQLException {
		throw DbException.get(ErrorCode.FEATURE_NOT_SUPPORTED).getSQLException();
	}

	@Override
	public <T> T unwrap(Class<T> iface) throws SQLException {
		throw DbException.get(ErrorCode.FEATURE_NOT_SUPPORTED).getSQLException();
	}

	protected void checkClosed() throws SQLException{
		if(isClosed)
			DbException.get(ErrorCode.OBJECT_CLOSED);

	}

	protected SQLException logAndConvert(Exception ex) {
		SQLException e = DbException.toSQLException(ex);
		return e;
	}
}
